name: List Environment Variables
on:
  workflow_dispatch:
 ## push:
 #   branches: [ main ]
 # pull_request:
 #   branches: [ main ]

jobs:
    ubuntu-environment-variables:
       runs-on: ubuntu-latest
       steps:
        - run : env